name: Build C++ Application

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Choose an appropriate runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile C++ Code
      id: compile
      run: |
        g++ -o myprogram Games/Chess/Chess_Board.cpp
        echo "::set-output name=exePath::$(pwd)/myprogram"
      shell: bash

    - name: Make Executable
      run: |
        exePath="${{ steps.compile.outputs.exePath }}"
        chmod +x "$exePath"
      if: steps.compile.outputs.exePath != ''

    - name: Use Compiled Executable
      run: |
        exePath="${{ steps.compile.outputs.exePath }}"
        echo "Executable Path: $exePath"
        if [[ -f "$exePath" ]]; then
          ./$exePath
        else
          echo "Executable not found at path: $exePath"
        fi
