name: Build C++ Application

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: windows-latest  # Use the windows-latest runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile C++ Code
      id: compile
      run: |
        g++ -o myprogram.exe Games/Chess/Chess_Board.cpp
        echo "::set-output name=exePath::$(pwd)/myprogram.exe"
      shell: bash

    - name: Use Compiled Executable
      run: |
        exePath="${{ steps.compile.outputs.exePath }}"
        echo "Executable Path: $exePath"
        if [[ -f "$exePath" ]]; then
          "$exePath"
        else
          echo "Executable not found at path: $exePath"
        fi
