name: Build C++ Application

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile C++ Code
      id: compile
      run: |
        g++ -o myprogram.exe Games/Chess/Chess_Board.cpp
        echo "::set-output name=exePath::$(pwd)/myprogram.exe"
      shell: bash
    - name: Debug
      run: |
        echo "Executable Path: ${{ steps.compile.outputs.exePath }}"
        if exist "${{ steps.compile.outputs.exePath }}" (
         cmd /c "${{ steps.compile.outputs.exePath }}"
         ) else (
          echo "Executable not found at path: ${{ steps.compile.outputs.exePath }}"
          )

