name: Compile and Run C++

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up g++
      run: sudo apt-get install g++

    - name: Compile and Run
      run: |
        g++ -o my_program Games/Chess/Chess_Board.cpp
        echo "::set-output name=exePath::$(pwd)/myprogram"
    - name: Use Compiled Executable
      run: |
        echo "Executable Path: ${{ steps.compile.outputs.exePath }}"
        # Now you can use ${{ steps.compile.outputs.exePath }} in your workflow
        # For example, you can run the compiled executable here
        ./${{ steps.compile.outputs.exePath }}
