name: Compile and Run C++

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up g++
      run: sudo apt-get install g++

    - name: Compile and Run
      run: |
        g++ -o my_program Games/Chess/Chess_Board.cpp
        ./my_program.exe
